-- 1. Storage Bucket 설정 (프로필 이미지용)
insert into storage.buckets (id, name, public)
values ('profile-images', 'profile-images', true);

-- 이미지 업로드 정책 설정
create policy "Public Access"
  on storage.objects for select
  using ( bucket_id = 'profile-images' );

create policy "Authenticated users can upload images"
  on storage.objects for insert
  with check ( bucket_id = 'profile-images' and auth.role() = 'authenticated' );

-- 2. Community Tables 설정

-- community_posts 테이블
create table if not exists public.community_posts (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  user_id uuid references auth.users not null,
  author_name text,
  avatar_url text,
  title text,
  content text,
  image_url text,
  likes integer default 0,
  views integer default 0,
  category text,
  age integer,
  location text,
  job text,
  gender text,
  bio text,
  school text
);

-- community_post_likes 테이블
create table if not exists public.community_post_likes (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  user_id uuid references auth.users not null,
  post_id bigint references public.community_posts(id) on delete cascade
);

-- post_comments 테이블
create table if not exists public.post_comments (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  post_id bigint references public.community_posts(id) on delete cascade,
  user_id uuid references auth.users not null,
  author_name text,
  avatar_url text,
  content text,
  likes integer default 0
);

-- RLS (Row Level Security) 설정
alter table public.community_posts enable row level security;
alter table public.community_post_likes enable row level security;
alter table public.post_comments enable row level security;

-- Policies
create policy "Public posts access"
  on public.community_posts for select
  using ( true );

create policy "Authenticated users can create posts"
  on public.community_posts for insert
  with check ( auth.role() = 'authenticated' );

create policy "Users can update own posts"
  on public.community_posts for update
  using ( auth.uid() = user_id );

create policy "Public likes access"
  on public.community_post_likes for select
  using ( true );

create policy "Authenticated users can like"
  on public.community_post_likes for insert
  with check ( auth.role() = 'authenticated' );

create policy "Users can unlike"
  on public.community_post_likes for delete
  using ( auth.uid() = user_id );

create policy "Public comments access"
  on public.post_comments for select
  using ( true );

create policy "Authenticated users can comment"
  on public.post_comments for insert
  with check ( auth.role() = 'authenticated' );
